export const msgTableTitles = [
  {
    id: 'msg_grp_advertiser',
    name: 'Advertiser',
    sortingType: null,
    isApplySorting: true,
    applyFilter: true,
    dataProp: 'advertiser',
  },
  {
    id: 'msg_grp_brand',
    name: 'Brand',
    sortingType: null,
    isApplySorting: true,
    applyFilter: true,
    dataProp: 'brand',
  },
  {
    id: 'msg_grp_sub_brand',
    name: 'Sub-Brand',
    sortingType: null,
    isApplySorting: true,
    applyFilter: true,
    dataProp: 'sub_brand',
  },
  {
    id: 'msg_grp_name',
    name: 'Messaging Group Name',
    sortingType: null,
    isApplySorting: true,
    applyFilter: true,
    dataProp: 'name',
  },
  {
    id: 'segments',
    name: 'Segments Included',
    isApplySorting: false,
    applyFilter: false,
  },
  {
    id: 'msg_grp_household_count',
    name: 'Household Count',
    sortingType: null,
    isApplySorting: true,
    applyFilter: true,
    dataProp: 'wanted_household_count',
  },
  {
    id: 'msg_grp_creative_name',
    name: 'Creative Name',
    sortingType: null,
    isApplySorting: true,
    applyFilter: true,
    dataProp: 'creative_name',
  },
  {
    id: 'msg_grp_isci_code',
    name: 'ISCI',
    sortingType: null,
    isApplySorting: true,
    applyFilter: true,
    dataProp: 'isci_code',
  },
  {
    id: 'video',
    name: 'Creative',
    isApplySorting: false,
    applyFilter: false,
  },
  {
    id: 'action',
    name: 'Action',
    isApplySorting: false,
    applyFilter: false,
  },
];
