export const manageCreativesTableTitles = [
  {
    id: 'op_cr_creative_thumbnail',
    name: 'Creative',
    applyFilter: false,
  },
  {
    id: 'op_cr_advertiser',
    name: 'Advertiser',
    applyFilter: true,
    dataProp: 'company_name',
    sortingType: true,
    isApplySorting: true,
  },
  {
    id: 'op_cr_brand_name',
    name: 'Brand',
    applyFilter: true,
    dataProp: 'brand_name',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'op_cr_creative_name',
    name: 'Creative Name',
    applyFilter: true,
    dataProp: 'ad_name',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'op_cr_isci_code',
    name: 'ISCI Code',
    applyFilter: true,
    dataProp: 'identifier',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'owner',
    name: 'Inventory Owner',
    applyFilter: true,
    dataProp: 'owner',
    sortingType: null,
    isApplySorting: false,
  },
  {
    id: 'op_cr_asset_id',
    name: 'Asset ID',
    applyFilter: true,
    dataProp: 'asset_id',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'ad_type',
    name: 'Ad Type',
    applyFilter: true,
    dataProp: 'ad_type',
    sortingType: null,
    isApplySorting: false,
  },
  {
    id: 'order',
    name: 'Order Type',
    applyFilter: true,
    dataProp: 'order_type',
    sortingType: null,
    isApplySorting: false,
  },

  {
    id: 'op_cr_delivery_vendor',
    name: 'Digital Delivery Vendor',
    applyFilter: true,
    dataProp: 'delivery_vendor',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'op_cr_duration',
    name: 'Duration',
    applyFilter: true,
    dataProp: 'actual_duration',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'op_cr_operator_creative_received',
    name: 'Creative Received?',
    applyFilter: true,
    dataProp: 'creative_received',
    sortingType: null,
    isApplySorting: false,
  },
  {
    id: 'op_cr_operator_creative_encoded',
    name: 'Encoded and moved to Ads-out Folder?',
    applyFilter: true,
    dataProp: 'encoding_received',
    sortingType: null,
    isApplySorting: false,
  },
];
