export const tableHeaderList = [
  {
    id: 'nt_cr_creative_thumbnail',
    name: 'Creative',
    applyFilter: false,
  },
  {
    id: 'nt_cr_advertiser',
    name: 'Advertiser',
    applyFilter: true,
    dataProp: 'company_name',
    sortingType: true,
    isApplySorting: true,
  },
  {
    id: 'ad_type',
    name: 'Ad Type',
    applyFilter: true,
    dataProp: 'ad_type',
    sortingType: null,
    isApplySorting: true,
  },

  {
    id: 'nt_cr_creative_name',
    name: 'Creative Name',
    applyFilter: true,
    dataProp: 'ad_name',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'nt_cr_isci_code',
    name: 'Ad-ID/ House #',
    applyFilter: true,
    dataProp: 'identifier',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'nt_cr_delivery_vendor',
    name: 'Digital Delivery Vendor',
    applyFilter: true,
    dataProp: 'delivery_vendor',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'nt_cr_duration',
    name: 'Duration',
    applyFilter: true,
    dataProp: 'actual_duration',
    sortingType: null,
    isApplySorting: true,
  },
  // {
  //   id: 'water_mark',
  //   name: 'Watermark/ fingerprint',
  //   applyFilter: true,
  //   dataProp: 'water_mark',
  //   sortingType: null,
  //   isApplySorting: true,
  // },
  // {
  //   id: 'down_prew',
  //   name: 'Media File Info',
  //   applyFilter: false,
  //   dataProp: 'down_prew',
  //   sortingType: false,
  //   isApplySorting: false,
  //   colSpan: 2,
  // },
  // {
  //   id: 'preview',
  //   name: 'Preview',
  //   applyFilter: false,
  //   dataProp: 'preview',
  //   sortingType: false,
  //   isApplySorting: false,
  //   // colSpan: 2,
  // },

  // {
  //   id: 'status',
  //   name: 'Status',
  //   applyFilter: true,
  //   dataProp: 'status',
  //   sortingType: null,
  //   isApplySorting: true,
  //   colSpan: '',
  // },
  {
    id: 'received',
    name: 'Confirmed by Distribution',
    applyFilter: true,
    dataProp: 'received',
    sortingType: null,
    isApplySorting: true,
    colSpan: '',
  },
];
