export const manageSegmentTagTitles = [
  {
    id: 'tag_advertiser',
    name: 'Advertiser',
    applyFilter: true,
    dataProp: 'advertiser',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'tag_deafault_brand',
    name: 'Brand',
    applyFilter: true,
    dataProp: 'brand',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'tag_data_provider',
    name: 'Data Provider',
    applyFilter: true,
    dataProp: 'data_provider',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'tag_order_type',
    name: 'Order Type',
    applyFilter: true,
    dataProp: 'order_type',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'tag_adcuratio_tag_name',
    name: 'Adcuratio Tag Name',
    applyFilter: true,
    dataProp: 'dish_filename',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'tag_order_name',
    name: 'Order Name',
    applyFilter: true,
    dataProp: 'order_name',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'tag_attribute_id',
    name: 'Attribute ID',
    applyFilter: true,
    dataProp: 'attribute_id',
    sortingType: null,
    isApplySorting: false,
  },
  {
    id: 'tag_row_count',
    name: 'Row Count',
    applyFilter: true,
    dataProp: 'row_count',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'tag_confirmation_tag_status',
    name: 'Confirmation Tagging Complete',
    applyFilter: false,
    sortingType: null,
    isApplySorting: false,
  },
];
