export const tableHeaderList = [
  {
    id: 'nt_cr_creative_thumbnail',
    name: 'Creative',
    applyFilter: false,
  },
  {
    id: 'nt_cr_advertiser',
    name: 'Advertiser',
    applyFilter: true,
    dataProp: 'company_name',
    sortingType: true,
    isApplySorting: true,
  },
  {
    id: 'nt_cr_brand_name',
    name: 'Brand',
    applyFilter: true,
    dataProp: 'brand_name',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'nt_cr_sub_brand',
    name: 'Sub-Brand',
    applyFilter: true,
    dataProp: 'sub_brand_name',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'nt_cr_creative_name',
    name: 'Creative Name',
    applyFilter: true,
    dataProp: 'ad_name',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'nt_cr_isci_code',
    name: 'ISCI Code',
    applyFilter: true,
    dataProp: 'identifier',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'nt_cr_delivery_vendor',
    name: 'Digital Delivery Vendor',
    applyFilter: true,
    dataProp: 'delivery_vendor',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'nt_cr_duration',
    name: 'Duration',
    applyFilter: true,
    dataProp: 'actual_duration',
    sortingType: null,
    isApplySorting: true,
  },
  {
    id: 'nt_cr_channel',
    name: 'Network',
    applyFilter: true,
    dataProp: null,
    sortingType: null,
    isApplySorting: false,
  },
];
