export const tableHeaderList = [
  {
    id: 'cr_video',
    name: 'Creative',
    sortingType: null,
    isApplySorting: false,
    applyFilter: false,
  },
  {
    id: 'cr_advertiser',
    name: 'Advertiser',
    sortingType: null,
    isApplySorting: true,
    applyFilter: true,
    dataProp: 'company_name',
  },
  {
    id: 'cr_brand',
    name: 'Brand',
    sortingType: null,
    isApplySorting: true,
    applyFilter: true,
    dataProp: 'brand_name',
  },
  {
    id: 'cr_sub_brand',
    name: 'Sub Brand',
    sortingType: null,
    isApplySorting: true,
    applyFilter: true,
    dataProp: 'sub_brand_name',
  },
  {
    id: 'cr_name',
    name: 'Creative Name',
    sortingType: null,
    isApplySorting: true,
    applyFilter: true,
    dataProp: 'ad_name',
  },
  {
    id: 'cr_isci_code',
    name: 'ISCI Code',
    sortingType: null,
    isApplySorting: true,
    applyFilter: true,
    dataProp: 'identifier',
  },
  {
    id: 'cr_delivery_vendor',
    name: 'Digital Delivery Vendor',
    sortingType: null,
    isApplySorting: true,
    applyFilter: true,
    dataProp: 'delivery_vendor',
  },
  {
    id: 'cr_house_id',
    name: 'House ID',
    sortingType: null,
    isApplySorting: false,
    applyFilter: true,
    dataProp: 'house_id',
  },
  {
    id: 'cr_duration',
    name: 'Duration',
    sortingType: null,
    isApplySorting: true,
    applyFilter: true,
    dataProp: 'actual_duration',
  },
  {
    id: 'cr_networks_approved',
    name: 'Networks Approved',
    sortingType: null,
    isApplySorting: false,
    applyFilter: true,
    dataProp: 'searchApprovalData',
  },
];
